### ISSUE TITLE
[Overview Data] Calculate the overview data

### ISSUE THREAD

**Issue by pixelsbyeryc** [pixelsbyeryc/home-bills#9]
## To-do

- [x] Calculate the total bills for a month
- [x] Calculate the total of each spender
- [x] Calculate the total of each category
